package units

import (
	"math/rand"
	"sort"
	"ws/game"
	"ws/models"
)

var UNITS = []models.Unit{{ // Warfactory
	Name:       "Goblin Technic",
	Guild:      "Warfactory",
	Size:       0.24,
	Tier:       1,
	Price:      30,
	Food:       1,
	Atk:        [2]float64{13, 15},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      135,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
	Upgrades:   []string{"Goblin Welder"},
	Abilities:  map[string][]string{
	//game.Aura: {"Tectonic flame"},
	//game.BuffAura: {"Steel fur", "Demonic swiftness", "Demonic might"},
	//game.Assist: {"On spices"},
	//React: {"Welding arc"},
	//On_death: {"Orc driver"},
	},
}, {
	Name:       "Goblin Welder",
	Guild:      "",
	Size:       0.24,
	Tier:       11,
	Price:      170,
	Food:       1,
	Atk:        [2]float64{73, 75},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      860,
	MpReg:      1,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		//Aura: [Frost],
		game.React: {"Welding arc"},
	},
}, {
	Name:       "Orc Bruiser",
	Guild:      "Warfactory",
	Size:       0.25,
	Tier:       2,
	Price:      40,
	Food:       1,
	Atk:        [2]float64{15, 17},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      200,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{"Auto-armored Orc"},
	Abilities:  map[string][]string{
	//Assist: [Overclocking],
	//onHit: {"Splinter shot"}
	},
}, {
	Name:       "Auto-armored Orc",
	Guild:      "",
	Size:       0.3,
	Tier:       21,
	Price:      130,
	Food:       1,
	Atk:        [2]float64{76, 84},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Aspd:       1,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      770,
	MaxMp:      10,
	MpReg:      1,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  2.1,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Active: {"Rocket barrage"},
		//onHit: {"Splinter shot"}
	},
}, {
	Name:       "Turret",
	Guild:      "Warfactory",
	Size:       0.37,
	Tier:       3,
	Price:      90,
	Food:       1,
	Atk:        [2]float64{23, 27},
	AtkType:    game.Piercing,
	AtkRange:   5,
	Projectile: "turret_bullet",
	ProjSpeed:  7.5,
	ProjTraj:   "linear",
	MaxHp:      380,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{"Turret Plus Plus"},
	Abilities: map[string][]string{
		game.OnHit: {"Splinter shot"},
	},
}, {
	Name:       "Turret Plus Plus",
	Guild:      "",
	Size:       0.37,
	Tier:       31,
	Price:      160,
	Food:       2,
	Atk:        [2]float64{62, 68},
	AtkType:    game.Piercing,
	AtkRange:   5,
	Projectile: "turretpp_bullet",
	ProjSpeed:  8.5,
	ProjTraj:   "linear",
	MaxHp:      900,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.OnHit: {"Splinter shot"},
	},
}, {
	Name:       "Air-Scout",
	Guild:      "Warfactory",
	Size:       0.22,
	Tier:       4,
	Price:      130,
	Food:       1,
	Atk:        [2]float64{50, 60},
	AtkType:    game.Piercing,
	AtkRange:   3.5,
	Projectile: "airscout_missile",
	ProjSpeed:  4.5,
	ProjTraj:   "linear",
	MaxHp:      600,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
	Upgrades:   []string{"Telecopter"},
	Abilities: map[string][]string{
		game.BuffAura: {"Scope"},
		//game.AttackReplacer: {"Blessed quiver"},
		//game.Assist:         {"Heal"},
	},
}, {
	Name:       "Telecopter",
	Guild:      "",
	Size:       0.3,
	Tier:       41,
	Price:      170,
	Food:       2,
	Atk:        [2]float64{100, 140},
	AtkType:    game.Magic,
	AtkRange:   3.5,
	Projectile: "telecopter_missile",
	ProjSpeed:  4.5,
	ProjTraj:   "linear",
	MaxHp:      1200,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.BuffAura: {"Scope 2.0"},
		//game.OnHit: {"Solar spike"},
	},
}, {
	Name:       "Battle Chemist",
	Guild:      "Warfactory",
	Size:       0.25,
	Tier:       5,
	Price:      180,
	Food:       2,
	Atk:        [2]float64{40, 45},
	AtkType:    game.Normal,
	AtkRange:   0.2,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      900,
	Aspd:       0.5,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2.6,
	Upgrades:   []string{"Exo-Chemical Armor"},
}, {
	Name:       "Exo-Chemical Armor",
	Guild:      "",
	Size:       0.35,
	Tier:       51,
	Price:      220,
	Food:       4,
	Atk:        [2]float64{140, 160},
	AtkType:    game.Normal,
	AtkRange:   0.2,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1850,
	MaxMp:      30,
	MpReg:      1,
	Aspd:       1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  1.8,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Active: {"Overclocking"},
		//onHit: {"Splinter shot"}
	},
}, {
	Name:       "Ram Machine",
	Guild:      "Warfactory",
	Size:       0.5,
	Tier:       6,
	Price:      305,
	Food:       2,
	Atk:        [2]float64{130, 150},
	AtkType:    game.Siege,
	AtkRange:   0.8,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1350,
	Aspd:       1,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.4,
	Upgrades:   []string{"Assault Machine"},
	Abilities: map[string][]string{
		game.OnDeath: {"Orc driver"},
	},
}, {
	Name:       "Assault Machine",
	Guild:      "",
	Size:       0.5,
	Tier:       61,
	Price:      350,
	Food:       4,
	Atk:        [2]float64{252, 268},
	AtkType:    game.Siege,
	AtkRange:   3.25,
	Projectile: "assmachine_cannonball",
	ProjSpeed:  4.5,
	ProjTraj:   "linear",
	MaxHp:      2350,
	Aspd:       1,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.4,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.OnDeath: {"Auto-armored orc driver"},
	},
}, { // Order of Dragon
	Name:       "Acolyte",
	Guild:      "Order of Dragon",
	Size:       0.2,
	Tier:       1,
	Price:      15,
	Food:       1,
	Atk:        [2]float64{6, 9},
	AtkType:    game.Normal,
	AtkRange:   0.2,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      75,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2.1,
	Upgrades:   []string{"Chaplain"},
	Abilities:  map[string][]string{
	//game.BuffAura: {"Feast"},
	},
}, {
	Name:       "Chaplain",
	Guild:      "",
	Size:       0.2,
	Tier:       11,
	Price:      95,
	Food:       1,
	Atk:        [2]float64{50, 54},
	AtkType:    game.Normal,
	AtkRange:   0.2,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      535,
	MaxMp:      15,
	MpReg:      1,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Assist: {"Divine hymn"},
	},
}, {
	Name:       "Archer",
	Guild:      "Order of Dragon",
	Size:       0.21,
	Tier:       2,
	Price:      50,
	Food:       1,
	Atk:        [2]float64{12, 13},
	AtkType:    game.Piercing,
	AtkRange:   6,
	Projectile: "archer_arrow",
	ProjSpeed:  10,
	ProjStart:  [2]float64{0.05, -0.675},
	ProjTraj:   "parabolic",
	MaxHp:      180,
	Aspd:       0.5,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.9,
	Upgrades:   []string{"Elite Archer"},
	Abilities:  map[string][]string{
	//game.OnHit: {"Bouncing attack"},
	},
}, {
	Name:       "Elite Archer",
	Guild:      "",
	Size:       0.22,
	Tier:       21,
	Price:      160,
	Food:       2,
	Atk:        [2]float64{18, 18},
	AtkType:    game.Piercing,
	AtkRange:   6,
	Projectile: "elarcher_arrow",
	ProjSpeed:  10,
	ProjStart:  [2]float64{0.5, 0.35},
	ProjTraj:   "parabolic",
	MaxHp:      550,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.9,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.AttackReplacer: {"Blessed quiver"},
	},
}, {
	Name:       "Footman",
	Guild:      "Order of Dragon",
	Size:       0.24,
	Tier:       3,
	Price:      80,
	Food:       1,
	Atk:        [2]float64{42, 44},
	AtkType:    game.Normal,
	AtkRange:   0.2,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      385,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{"Guardian"},
	Abilities:  map[string][]string{},
}, {
	Name:       "Guardian",
	Guild:      "",
	Size:       0.24,
	Tier:       31,
	Price:      160,
	Food:       1,
	Atk:        [2]float64{60, 66},
	AtkType:    game.Normal,
	AtkRange:   0.19,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1150,
	Aspd:       0.6,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Defensive: {"Great shield"},
	},
}, {
	Name:       "Priest",
	Guild:      "Order of Dragon",
	Size:       0.26,
	Tier:       4,
	Price:      130,
	Food:       1,
	Atk:        [2]float64{53, 63},
	AtkType:    game.Magic,
	AtkRange:   5,
	Projectile: "priest_missile",
	ProjSpeed:  7.5,
	ProjStart:  [2]float64{0.15, -0.675},
	ProjTraj:   "linear",
	MaxHp:      420,
	MaxMp:      10,
	MpReg:      1,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{"High Priest"},
	Abilities: map[string][]string{
		game.Assist: {"Heal"},
	},
}, {
	Name:       "High Priest",
	Guild:      "",
	Size:       0.26,
	Tier:       41,
	Price:      170,
	Food:       2,
	Atk:        [2]float64{118, 136},
	AtkType:    game.Magic,
	AtkRange:   5,
	Projectile: "hpriest_missile",
	ProjSpeed:  7.5,
	ProjStart:  [2]float64{0.15, -0.675},
	ProjTraj:   "linear",
	MaxHp:      840,
	MaxMp:      10,
	MpReg:      1,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Assist: {"Greater heal"},
	},
}, {
	Name:       "Knight",
	Guild:      "Order of Dragon",
	Size:       0.36,
	Tier:       5,
	Price:      200,
	Food:       1,
	Atk:        [2]float64{70, 80},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      880,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2.2,
	Upgrades:   []string{"Lord Knight"},
	Abilities:  map[string][]string{
	//game.OnHit: {"_(OnHit)Feast"},
	},
}, {
	Name:       "Lord Knight",
	Guild:      "",
	Size:       0.36,
	Tier:       51,
	Price:      220,
	Food:       3,
	Atk:        [2]float64{180, 191},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1770,
	Aspd:       1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2.1,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Defensive: {"Heavy plate"},
	},
}, {
	Name:       "Sky Rider",
	Guild:      "Order of Dragon",
	Size:       0.25,
	Tier:       6,
	Price:      320,
	Food:       2,
	Atk:        [2]float64{120, 128},
	AtkType:    game.Magic,
	AtkRange:   1,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1480,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{"Sky Templar"},
	Abilities:  map[string][]string{},
}, {
	Name:       "Sky Templar",
	Guild:      "",
	Size:       0.25,
	Tier:       61,
	Price:      360,
	Food:       4,
	Atk:        [2]float64{300, 300},
	AtkType:    game.Magic,
	AtkRange:   3,
	Projectile: "skytemplar_sunspear",
	ProjSpeed:  4.5,
	ProjTraj:   "linear",
	MaxHp:      2675,
	Aspd:       1.5,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.OnHit: {"Solar spike"},
	},
}, { // Elemental coven
	Name:       "Twinkle",
	Guild:      "Elemental Coven",
	Size:       0.15,
	Tier:       1,
	Price:      20,
	Food:       1,
	Atk:        [2]float64{13, 13},
	AtkType:    game.Chaos,
	AtkRange:   2.5,
	Projectile: "twinkle_missile",
	ProjSpeed:  1,
	MaxHp:      100,
	Aspd:       1.25,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{"Wisp"},
	Abilities:  map[string][]string{},
}, {
	Name:       "Wisp",
	Guild:      "",
	Size:       0.15,
	Tier:       11,
	Price:      140,
	Food:       1,
	Atk:        [2]float64{100, 100},
	AtkType:    game.Chaos,
	AtkRange:   2.5,
	Projectile: "wisp_missile",
	ProjSpeed:  1,
	MaxHp:      560,
	Aspd:       1.45,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.8,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Spirit of Storm",
	Guild:      "Elemental Coven",
	Size:       0.2,
	Tier:       2,
	Price:      50,
	Food:       1,
	Atk:        [2]float64{13, 18},
	AtkType:    game.Normal,
	AtkRange:   3.75,
	Projectile: "sostorm_missile",
	ProjSpeed:  5,
	MaxHp:      175,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{"Thunder Lord"},
	Abilities: map[string][]string{
		game.OnHit: {"Bouncing sparks"},
	},
}, {
	Name:       "Thunder Lord",
	Guild:      "",
	Size:       0.2,
	Tier:       21,
	Price:      130,
	Food:       1,
	Atk:        [2]float64{49, 54},
	AtkType:    game.Normal,
	AtkRange:   3.75,
	Projectile: "tlord_missile",
	ProjSpeed:  6,
	MaxHp:      575,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.OnHit: {"Booming charges"},
	},
}, {
	Name:       "Incinerator",
	Guild:      "Elemental Coven",
	Size:       0.2,
	Tier:       3,
	Price:      80,
	Food:       1,
	Atk:        [2]float64{36, 42},
	AtkType:    game.Magic,
	AtkRange:   3.0,
	Projectile: "incinerator_missile",
	ProjSpeed:  7,
	MaxHp:      335,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2,
	Upgrades:   []string{"Cindercore"},
	Abilities:  map[string][]string{},
}, {
	Name:       "Cindercore",
	Guild:      "",
	Size:       0.2,
	Tier:       31,
	Price:      120,
	Food:       2,
	Atk:        [2]float64{51, 61},
	AtkType:    game.Magic,
	AtkRange:   3.0,
	Projectile: "cindercore_missile",
	ProjSpeed:  7,
	MaxHp:      850,
	MaxMp:      3,
	MpReg:      3,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Active: {"Burning embers"},
	},
}, {
	Name:       "Earthstomper",
	Guild:      "Elemental Coven",
	Size:       0.3,
	Tier:       4,
	Price:      130,
	Food:       1,
	Atk:        [2]float64{75, 81},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      735,
	Aspd:       1.1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2,
	Upgrades:   []string{"Rockcracker"},
	Abilities:  map[string][]string{},
}, {
	Name:       "Rockcracker",
	Guild:      "",
	Size:       0.31,
	Tier:       41,
	Price:      170,
	Food:       2,
	Atk:        [2]float64{166, 180},
	AtkType:    game.Siege,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1490,
	Aspd:       1.1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Follower",
	Guild:      "Elemental Coven",
	Size:       0.2,
	Tier:       5,
	Price:      200,
	Food:       2,
	Atk:        [2]float64{57, 71},
	AtkType:    game.Piercing,
	AtkRange:   5.5,
	Projectile: "follower_missile",
	ProjSpeed:  11,
	MaxHp:      670,
	MaxMp:      50,
	MpReg:      2,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2,
	Upgrades:   []string{"Master Sorcerer"},
	Abilities: map[string][]string{
		game.AttackReplacer: {"Spell blast"},
	},
}, {
	Name:       "Master Sorcerer",
	Guild:      "",
	Size:       0.2,
	Tier:       51,
	Price:      260,
	Food:       3,
	Atk:        [2]float64{119, 125},
	AtkType:    game.Magic,
	AtkRange:   5.5,
	Projectile: "msorcerer_missile",
	ProjSpeed:  11,
	MaxHp:      1085,
	MaxMp:      50,
	MpReg:      2,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.AttackReplacer: {"Spell blast"},
		game.BuffAura:       {"Mana tides"},
	},
}, {
	Name:       "Shadow Spirit",
	Guild:      "Elemental Coven",
	Size:       0.2,
	Tier:       6,
	Price:      320,
	Food:       2,
	Atk:        [2]float64{142, 156},
	AtkType:    game.Magic,
	AtkRange:   4,
	Projectile: "sspirit_missile",
	ProjSpeed:  11,
	MaxHp:      1050,
	MaxMp:      160,
	MpReg:      2,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{"Grim Shade"},
	Abilities: map[string][]string{
		game.Defensive: {"Illusive barrier"},
	},
}, {
	Name:       "Grim Shade",
	Guild:      "",
	Size:       0.2,
	Tier:       61,
	Price:      350,
	Food:       4,
	Atk:        [2]float64{193, 205},
	AtkType:    game.Magic,
	AtkRange:   4,
	Projectile: "gshade_missile",
	ProjSpeed:  11,
	MaxHp:      1700,
	MaxMp:      350,
	MpReg:      3,
	Aspd:       0.98,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
	Upgrades:   []string{},
	Abilities: map[string][]string{
		game.Offensive: {"Illusive impulse"},
		game.Defensive: {"Illusive barrier"},
	},
}, { // Shadow Syndicate
	Name:       "Criminal Scum",
	Guild:      "",
	Size:       0.1,
	Tier:       11,
	Price:      20,
	Food:       1,
	Atk:        [2]float64{10, 12},
	AtkType:    game.Normal,
	AtkRange:   1,
	Projectile: "cscum_knife",
	ProjSpeed:  1,
	MaxHp:      90,
	Aspd:       0.7,
	Def:        3,
	DefType:    game.Unarmored,
	Movespeed:  2.75,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Deserter",
	Guild:      "",
	Size:       0.2,
	Tier:       22,
	Price:      40,
	Food:       1,
	Atk:        [2]float64{18, 20},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      210,
	Aspd:       1,
	Def:        4,
	DefType:    game.Light,
	Movespeed:  1.9,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Knife Thrower",
	Guild:      "",
	Size:       0.15,
	Tier:       33,
	Price:      80,
	Food:       1,
	Atk:        [2]float64{16, 24},
	AtkType:    game.Piercing,
	AtkRange:   4,
	Projectile: "kthrower_knife",
	ProjSpeed:  3.5,
	MaxHp:      210,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
	Upgrades:   []string{},
	Abilities:  map[string][]string{
	//game.OnHit: {"Silver edge"},
	},
}, {
	Name:       "Convict",
	Guild:      "",
	Size:       0.15,
	Tier:       44,
	Price:      125,
	Food:       1,
	Atk:        [2]float64{41, 47},
	AtkType:    game.Chaos,
	AtkRange:   0.3,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      550,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.5,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Renegade Mage",
	Guild:      "",
	Size:       0.15,
	Tier:       55,
	Price:      200,
	Food:       2,
	Atk:        [2]float64{76, 84},
	AtkType:    game.Magic,
	AtkRange:   5,
	Projectile: "rmage_missile",
	ProjSpeed:  10,
	MaxHp:      815,
	Aspd:       1,
	Def:        3,
	DefType:    game.Unarmored,
	Movespeed:  1.8,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, {
	Name:       "Assasin",
	Guild:      "",
	Size:       0.15,
	Tier:       66,
	Price:      300,
	Food:       2,
	Atk:        [2]float64{79, 89},
	AtkType:    game.Normal,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1350,
	Aspd:       0.6,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2.5,
	Upgrades:   []string{},
	Abilities:  map[string][]string{},
}, { // Wave 1
	Name:       "Giant Ant",
	Guild:      "",
	Size:       0.225,
	Tier:       0,
	Bounty:     3,
	Price:      0,
	Atk:        [2]float64{3, 4},
	AtkType:    game.Piercing,
	AtkRange:   0.3,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      34,
	Aspd:       1.25,
	Def:        3,
	DefType:    game.Unarmored,
	Movespeed:  2.5,
	Abilities:  map[string][]string{
	//game.OnHit: {"Corruption"},
	//React: {"Welding arc"},
	//game.Assist:   {"Overclocking"},
	//"buffAura": {"Commander aura"},
	},
}, { // Wave 2
	Name:       "Bat",
	Guild:      "",
	Size:       0.2,
	Tier:       0,
	Bounty:     3,
	Price:      0,
	Atk:        [2]float64{3, 5},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      40,
	Aspd:       1,
	Def:        3,
	DefType:    game.Unarmored,
	Movespeed:  2,
}, { // Wave 3
	Name:       "Slime",
	Guild:      "",
	Size:       0.25,
	Tier:       0,
	Bounty:     4,
	Price:      0,
	Atk:        [2]float64{6, 8},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      63,
	Aspd:       1.1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
}, { // Wave 4
	Name:       "Snake",
	Guild:      "",
	Size:       0.2,
	Tier:       0,
	Bounty:     5,
	Price:      0,
	Atk:        [2]float64{5, 7},
	AtkType:    game.Piercing,
	AtkRange:   3.5,
	Projectile: "snake_spittle",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      75,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  1.5,
}, { // Wave 5
	Name:       "Vulture",
	Guild:      "",
	Size:       0.2,
	Tier:       0,
	Bounty:     5,
	Price:      0,
	Atk:        [2]float64{8, 10},
	AtkType:    game.Magic,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      115,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.4,
}, { // Wave 6
	Name:       "Boulder",
	Guild:      "",
	Size:       0.25,
	Tier:       0,
	Bounty:     5,
	Price:      0,
	Atk:        [2]float64{19, 20},
	AtkType:    game.Siege,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      138,
	Aspd:       1.3,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.36,
}, { // Wave 7
	Name:       "Predator",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     6,
	Price:      0,
	Atk:        [2]float64{25, 27},
	AtkType:    game.Piercing,
	AtkRange:   0.3,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      213,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2.9,
}, { // Wave 8
	Name:       "Cultist",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     6,
	Price:      0,
	Atk:        [2]float64{13, 17},
	AtkType:    game.Magic,
	AtkRange:   3.5,
	Projectile: "klesch_spittle",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      178,
	Aspd:       1,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
}, { // Wave 9
	Name:       "Brigand",
	Guild:      "",
	Size:       0.22,
	Tier:       0,
	Bounty:     5,
	Price:      0,
	Atk:        [2]float64{22, 24},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      210,
	Aspd:       1.1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  1.36,
}, { // Wave 10
	Name:       "Goblin Leader",
	Guild:      "",
	Size:       0.5,
	Tier:       0,
	Bounty:     51,
	Price:      0,
	Atk:        [2]float64{153, 189},
	AtkType:    game.Chaos,
	AtkRange:   0.8,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      3000,
	Aspd:       0.7,
	Def:        1,
	DefType:    game.Light,
	Movespeed:  1.86,
}, { // Wave 11
	Name:       "Mech Goblin",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     5,
	Price:      0,
	Atk:        [2]float64{15, 17},
	AtkType:    game.Siege,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      230,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.7,
}, { // Wave 12
	Name:       "Mermaid",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     6,
	Price:      0,
	Atk:        [2]float64{16, 18},
	AtkType:    game.Piercing,
	AtkRange:   3.5,
	Projectile: "mermaid_arrow",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      241,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  1.9,
}, { // Wave 13
	Name:       "Wyrm",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     7,
	Price:      0,
	Atk:        [2]float64{30, 33},
	AtkType:    game.Magic,
	AtkRange:   0.35,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      285,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2,
}, { // Wave 14
	Name:       "Walrus",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     12,
	Price:      0,
	Atk:        [2]float64{82, 86},
	AtkType:    game.Normal,
	AtkRange:   0.3,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      640,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
}, { // Wave 15
	Name:       "Centaur",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     9,
	Price:      0,
	Atk:        [2]float64{78, 84},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      515,
	Aspd:       1.5,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  1.9,
}, { //Wave 16
	Name:       "Magic Lizard",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     8,
	Price:      0,
	Atk:        [2]float64{34, 40},
	AtkType:    game.Magic,
	AtkRange:   4,
	Projectile: "mlizard_missile",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      347,
	Aspd:       1,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  1.9,
}, { // Wave 17
	Name:       "Flesh Golem",
	Guild:      "",
	Size:       0.25,
	Tier:       0,
	Bounty:     10,
	Price:      0,
	Atk:        [2]float64{83, 87},
	AtkType:    game.Siege,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      699,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.9,
}, { // Wave 18
	Name:       "Thing",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     8,
	Price:      0,
	Atk:        [2]float64{47, 54},
	AtkType:    game.Magic,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      780,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
}, { // Wave 19
	Name:       "Spiderling",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     10,
	Price:      0,
	Atk:        [2]float64{70, 73},
	AtkType:    game.Piercing,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      930,
	Aspd:       0.8,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2.2,
}, { // Wave 20
	Name:       "Warturtle",
	Guild:      "",
	Size:       0.55,
	Tier:       0,
	Bounty:     86,
	Price:      0,
	Atk:        [2]float64{186, 221},
	AtkType:    game.Chaos,
	AtkRange:   4,
	Projectile: "warturtle_spittle",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      7100,
	Aspd:       0.51,
	Def:        7,
	DefType:    game.Heavy,
	Movespeed:  1.66,
	Abilities: map[string][]string{
		game.OnHit: {"Split splash"},
	},
}, { // Wave 21
	Name:       "Hyppogryph",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     10,
	Price:      0,
	Atk:        [2]float64{53, 63},
	AtkType:    game.Piercing,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      949,
	Aspd:       0.6,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2,
}, { // Wave 22
	Name:       "Mammoth",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     9,
	Price:      0,
	Atk:        [2]float64{99, 108},
	AtkType:    game.Siege,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      850,
	Aspd:       1.4,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.9,
}, { // Wave 23
	Name:       "Wildkin",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     11,
	Price:      0,
	Atk:        [2]float64{102, 114},
	AtkType:    game.Normal,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1450,
	Aspd:       1.1,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2,
}, { // Wave 24
	Name:       "Revenant",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     11,
	Price:      0,
	Atk:        [2]float64{89, 99},
	AtkType:    game.Magic,
	AtkRange:   4,
	Projectile: "revenant_missile",
	ProjSpeed:  10,
	ProjTraj:   "linear",
	MaxHp:      1350,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2.1,
}, { // Wave 25
	Name:       "Succubus",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     9,
	Price:      0,
	Atk:        [2]float64{80, 86},
	AtkType:    game.Piercing,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1580,
	Aspd:       0.7,
	Def:        3,
	DefType:    game.Light,
	Movespeed:  2.2,
}, { // Wave 26
	Name:       "Myrmidon",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     12,
	Price:      0,
	Atk:        [2]float64{161, 171},
	AtkType:    game.Normal,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1932,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2,
}, { // Wave 27
	Name:       "Doom Guard",
	Guild:      "",
	Size:       0.15,
	Tier:       0,
	Bounty:     12,
	Price:      0,
	Atk:        [2]float64{121, 129},
	AtkType:    game.Normal,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      2159,
	Aspd:       0.85,
	Def:        3,
	DefType:    game.Medium,
	Movespeed:  2,
}, { // Wave 28
	Name:       "Juggernaut",
	Guild:      "",
	Size:       0.25,
	Tier:       0,
	Bounty:     23,
	Price:      0,
	Atk:        [2]float64{182, 202},
	AtkType:    game.Siege,
	AtkRange:   4,
	Projectile: "juggernaut_missile",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      3700,
	Aspd:       0.9,
	Def:        3,
	DefType:    game.Fortified,
	Movespeed:  1.5,
}, { // Wave 29
	Name:       "Frost Wyrm",
	Guild:      "",
	Size:       0.2,
	Tier:       0,
	Bounty:     14,
	Price:      0,
	Atk:        [2]float64{210, 230},
	AtkType:    game.Magic,
	AtkRange:   2,
	Projectile: "fwyrm_breath",
	ProjSpeed:  3,
	ProjTraj:   "linear",
	MaxHp:      2732,
	Aspd:       1.2,
	Def:        3,
	DefType:    game.Heavy,
	Movespeed:  2,
}, { // Wave 30
	Name:       "Magnataur",
	Guild:      "",
	Size:       0.55,
	Tier:       0,
	Bounty:     123,
	Price:      0,
	Atk:        [2]float64{736, 802},
	AtkType:    game.Chaos,
	AtkRange:   0.5,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      17055,
	Aspd:       0.45,
	Def:        7,
	DefType:    game.Fortified,
	Movespeed:  2,
}, { // Wave 31
	Name:       "Lisk",
	Guild:      "",
	Size:       0.1,
	Tier:       0,
	Bounty:     0,
	Price:      0,
	Atk:        [2]float64{248, 269},
	AtkType:    game.Chaos,
	AtkRange:   4,
	Projectile: "harchok",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      3070,
	Aspd:       1,
	Def:        20,
	DefType:    game.Unarmored,
	Movespeed:  1,
}, {
	Name:       "Militia",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     1,
	Price:      20,
	Atk:        [2]float64{4, 6},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      50,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.0,
}, {
	Name:       "Marksman",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     2,
	Price:      40,
	Atk:        [2]float64{8, 10},
	AtkType:    game.Piercing,
	AtkRange:   4,
	Projectile: "marksman_arrow",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      70,
	Aspd:       0.9,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  1.9,
}, {
	Name:       "Swordsman",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     2,
	Price:      40,
	Atk:        [2]float64{10, 14},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      105,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Medium,
	Movespeed:  2.23,
}, {
	Name:       "Rogue",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     2,
	Price:      60,
	Atk:        [2]float64{21, 23},
	AtkType:    game.Normal,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      155,
	Aspd:       1.3,
	Def:        0,
	DefType:    game.Heavy,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.OnHit: {"Bash"},
	},
}, {
	Name:       "Lizard",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     5,
	Price:      100,
	Atk:        [2]float64{37, 43},
	AtkType:    game.Piercing,
	AtkRange:   0.225,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      260,
	Aspd:       1.4,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.0,
}, {
	Name:       "Hermit",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     4,
	Price:      100,
	Atk:        [2]float64{25, 27},
	AtkType:    game.Magic,
	AtkRange:   2.5,
	Projectile: "hermit_missile",
	ProjSpeed:  3.5,
	ProjTraj:   "linear",
	MaxHp:      230,
	Aspd:       1.1,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.BuffAura: {"Breath of life"},
	},
}, {
	Name:       "Spearman",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     6,
	Price:      120,
	Atk:        [2]float64{31, 35},
	AtkType:    game.Piercing,
	AtkRange:   2.5,
	Projectile: "spearman_spear",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      275,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Medium,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.Offensive: {"Tyrannicide"},
	},
}, {
	Name:       "Commander",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     5,
	Price:      120,
	Atk:        [2]float64{30, 32},
	AtkType:    game.Piercing,
	AtkRange:   3,
	Projectile: "commander_spear",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      260,
	Aspd:       1.2,
	Def:        0,
	DefType:    game.Fortified,
	Movespeed:  2.1,
	Abilities: map[string][]string{
		game.BuffAura: {"Commander aura"},
	},
}, {
	Name:       "Furry Bear",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     6,
	Price:      140,
	Atk:        [2]float64{36, 50},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      390,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Medium,
	Movespeed:  2.1,
	Abilities: map[string][]string{
		game.BuffAura: {"Steel fur"},
	},
}, {
	Name:       "Flying Spearman",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     9,
	Price:      180,
	Atk:        [2]float64{41, 47},
	AtkType:    game.Piercing,
	AtkRange:   3,
	Projectile: "spearman_spear",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      390,
	Aspd:       1,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.1,
	Abilities:  map[string][]string{},
}, {
	Name:       "Catapult",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     10,
	Price:      200,
	Atk:        [2]float64{43, 47},
	AtkType:    game.Siege,
	AtkRange:   5.5,
	Projectile: "catapult_stone",
	ProjSpeed:  3,
	ProjTraj:   "parabolic",
	MaxHp:      260,
	Aspd:       1.8,
	Def:        0,
	DefType:    game.Fortified,
	Movespeed:  1.8,
	Abilities: map[string][]string{
		game.Offensive: {"Tyrannicide"},
	},
}, {
	Name:       "Plate Runner",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     10,
	Price:      200,
	Atk:        [2]float64{66, 72},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      515,
	Aspd:       1.2,
	Def:        0,
	DefType:    game.Heavy,
	Movespeed:  3.5,
	Abilities:  map[string][]string{},
}, {
	Name:       "Not-so-furry Wolf",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     12,
	Price:      240,
	Atk:        [2]float64{46, 54},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      650,
	Aspd:       0.7,
	Def:        0,
	DefType:    game.Medium,
	Movespeed:  2.1,
	Abilities: map[string][]string{
		game.Aura: {"Piercing howl"},
	},
}, {
	Name:       "Slow Troll",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     12,
	Price:      240,
	Atk:        [2]float64{54, 62},
	AtkType:    game.Piercing,
	AtkRange:   3,
	Projectile: "stroll_arrow",
	ProjSpeed:  6,
	ProjTraj:   "parabolic",
	MaxHp:      545,
	Aspd:       1.2,
	Def:        0,
	DefType:    game.Medium,
	Movespeed:  1.8,
	Abilities: map[string][]string{
		game.OnHit: {"Slowing arrows"},
	},
}, {
	Name:       "Warlock",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     14,
	Price:      300,
	Atk:        [2]float64{59, 67},
	AtkType:    game.Magic,
	AtkRange:   3,
	Projectile: "warlock_missile",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      585,
	Aspd:       1.25,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  1.8,
	Abilities: map[string][]string{
		game.OnHit: {"Corruption"},
	},
}, {
	Name:       "Extremely Furry Bear",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     15,
	Price:      300,
	Atk:        [2]float64{82, 90},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      775,
	HpReg:      5,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Heavy,
	Movespeed:  2,
	Abilities:  map[string][]string{},
}, {
	Name:       "Ballista",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     17,
	Price:      340,
	Atk:        [2]float64{88, 98},
	AtkType:    game.Siege,
	AtkRange:   5.5,
	Projectile: "ballista_spear",
	ProjSpeed:  11,
	ProjTraj:   "linear",
	MaxHp:      530,
	Aspd:       1.6,
	Def:        0,
	DefType:    game.Fortified,
	Movespeed:  1.6,
	Abilities: map[string][]string{
		game.Offensive: {"Tyrannicide"},
	},
}, {
	Name:       "Spice Merchant",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     18,
	Price:      400,
	Atk:        [2]float64{65, 73},
	AtkType:    game.Magic,
	AtkRange:   3,
	Projectile: "smerchant_missile",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      770,
	MaxMp:      20,
	MpReg:      2,
	Aspd:       0.9,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.Assist: {"On spices"},
	},
}, {
	Name:       "Flesheater",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     17,
	Price:      400,
	Atk:        [2]float64{141, 159},
	AtkType:    game.Normal,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1050,
	Aspd:       1.3,
	Def:        0,
	DefType:    game.Heavy,
	Movespeed:  1.9,
	Abilities: map[string][]string{
		game.BuffAura: {"Feast"},
	},
}, {
	Name:       "Monstrous Sparrow",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     22,
	Price:      440,
	Atk:        [2]float64{106, 116},
	AtkType:    game.Normal,
	AtkRange:   3,
	Projectile: "msparrow_spittle",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      920,
	Aspd:       1.0,
	Def:        0,
	DefType:    game.Light,
	Movespeed:  2.1,
	Abilities:  map[string][]string{},
}, {
	Name:       "Giant War Bear",
	Guild:      "",
	Size:       0.25,
	Tier:       game.Summon,
	Bounty:     25,
	Price:      500,
	Atk:        [2]float64{144, 155},
	AtkType:    game.Siege,
	AtkRange:   3,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      1420,
	Aspd:       1.3,
	Def:        0,
	DefType:    game.Fortified,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.BuffAura: {"Steel fur"},
	},
}, {
	Name:       "Something Strange",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     30,
	Price:      600,
	Atk:        [2]float64{131, 145},
	AtkType:    game.Piercing,
	AtkRange:   3,
	Projectile: "sstrange_spittle",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      1285,
	Aspd:       1.2,
	Def:        0,
	DefType:    game.Heavy,
	Movespeed:  1.8,
	Abilities: map[string][]string{
		game.OnHit:    {"Strange poison"},
		game.BuffAura: {"Strange regeneration"},
	},
}, {
	Name:       "Moving Mountain",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     50,
	Price:      1000,
	Atk:        [2]float64{155, 173},
	AtkType:    game.Chaos,
	AtkRange:   0.25,
	Projectile: game.Melee,
	ProjSpeed:  1,
	MaxHp:      2500,
	Aspd:       0.8,
	Def:        0,
	DefType:    game.Fortified,
	Movespeed:  2.0,
	Abilities: map[string][]string{
		game.OnHit: {"Blazing crush"},
		game.Aura:  {"Tectonic flame"},
	},
}, {
	Name:       "Dimon",
	Guild:      "",
	Size:       0.15,
	Tier:       game.Summon,
	Bounty:     70,
	Price:      1500,
	Atk:        [2]float64{221, 257},
	AtkType:    game.Chaos,
	AtkRange:   3,
	Projectile: "dimon_missile",
	ProjSpeed:  6,
	ProjTraj:   "linear",
	MaxHp:      3000,
	Aspd:       0.8,
	Def:        0,
	DefType:    game.Unarmored,
	Movespeed:  2.1,
	Abilities: map[string][]string{
		game.BuffAura: {"Demonic might", "Demonic swiftness"},
	},
}, {
	Name:  "Tier 1",
	Guild: game.Recruits,
	Price: 18,
	Food:  1,
}, {
	Name:  "Tier 2",
	Guild: game.Recruits,
	Price: 45,
	Food:  1,
}, {
	Name:  "Tier 3",
	Guild: game.Recruits,
	Price: 85,
	Food:  1,
}, {
	Name:  "Tier 4",
	Guild: game.Recruits,
	Price: 135,
	Food:  1,
}, {
	Name:  "Tier 5",
	Guild: game.Recruits,
	Price: 200,
	Food:  2,
}, {
	Name:  "Tier 6",
	Guild: game.Recruits,
	Price: 305,
	Food:  2,
}}

//HELPER STRUCTS
var GUILDS = []string{}
var UNITS_BY_NAME = map[string]models.Unit{}
var UNITS_BY_GUILD = map[string][]string{}
var UNITS_BY_TIER = map[int][]string{}

func RandomByTier(tier int) string {
	return UNITS_BY_TIER[tier][rand.Intn(len(UNITS_BY_TIER[tier]))]
}

func init() {
	aspdCoef := 1 / game.WAR_STEP_DELAY
	for _, unit := range UNITS {
		unit.Hp = unit.MaxHp
		unit.Mp = unit.MaxMp
		unit.HpReg = unit.HpReg * game.WAR_STEP_DELAY
		unit.MpReg = unit.MpReg * game.WAR_STEP_DELAY
		unit.Aspd = unit.Aspd * aspdCoef
		unit.Movespeed = unit.Movespeed * game.WAR_STEP_DELAY
		unit.ProjSpeed = unit.ProjSpeed * game.WAR_STEP_DELAY

		/*if unit.Tier == 0 {
			Nerf := 0.75
			unit.Atk[0] = unit.Atk[0] * Nerf
			unit.Atk[1] = unit.Atk[1] * Nerf
			unit.MaxHp = unit.MaxHp * Nerf
			unit.Hp = unit.Hp * Nerf
		}*/

		UNITS_BY_NAME[unit.Name] = unit

		if unit.Guild != "" {
			UNITS_BY_GUILD[unit.Guild] = append(UNITS_BY_GUILD[unit.Guild], unit.Name)
		}

		UNITS_BY_TIER[unit.Tier] = append(UNITS_BY_TIER[unit.Tier], unit.Name)
	}

	for guild, _ := range UNITS_BY_GUILD {
		if guild == game.Recruits {
			continue
		}
		GUILDS = append(GUILDS, guild)
	}
	sort.Strings(GUILDS)
	GUILDS = append(GUILDS, game.Draft)
	GUILDS = append(GUILDS, game.DynamicDraft)
	GUILDS = append(GUILDS, game.Recruits)
}
